[package]
name = "kamu-logging"
version = "1.2.2"
description = "Small helper crate to configure structured logging for IMMER's services using the tracing ecosystem."
documentation = "https://docs.rs/kamu-logging"
categories = ["asynchronous", "development-tools::debugging", "wasm"]
keywords = ["actix", "logging", "systemd", "tracing", "wasm"]
readme = "README.md"
license = "MIT OR Apache-2.0"
authors.workspace = true
edition.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["systemd", "with-actix-web"]
systemd = ["dep:console", "dep:tracing-journald", "dep:tracing-log", "dep:tracing-subscriber"]
wasm32 = ["dep:console_error_panic_hook", "dep:time", "dep:tracing-subscriber", "dep:tracing-web"]
with-actix-web = ["dep:actix-web", "dep:tracing-actix-web"]
with-otlp = [
  "dep:opentelemetry",
  "dep:opentelemetry-otlp",
  "dep:opentelemetry_sdk",
  "dep:tracing-opentelemetry",
]

[dependencies]
actix-web = { workspace = true, optional = true }
console = { workspace = true, optional = true }
console_error_panic_hook = { workspace = true, optional = true }
thiserror = { workspace = true, features = ["std"] }
time = { workspace = true, optional = true, features = ["wasm-bindgen"] }
tracing = { workspace = true }
tracing-actix-web = { workspace = true, optional = true }
tracing-journald = { workspace = true, optional = true }
tracing-log = { workspace = true, optional = true }
tracing-web = { workspace = true, optional = true }

opentelemetry = { workspace = true, optional = true, features = ["trace"] }
opentelemetry-otlp = { workspace = true, optional = true, features = [
  "http-proto",
  "reqwest-blocking-client",
  "trace",
] }
opentelemetry_sdk = { workspace = true, optional = true, features = ["trace"] }
tracing-opentelemetry = { workspace = true, optional = true, features = ["tracing-log"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = { workspace = true, optional = true, features = [
  "ansi",
  "chrono",
  "env-filter",
  "fmt",
  "json",
  "registry",
  "smallvec",
  "std",
  "tracing-log",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tracing-subscriber = { workspace = true, optional = true, features = [
  "alloc",
  "env-filter",
  "fmt",
  "json",
  "registry",
  "time",
] }

[dev-dependencies]
actix-web = { workspace = true, default-features = true }

[[example]]
name = "minimal"
required-features = ["systemd"]

[[example]]
name = "json_stdout"
required-features = ["systemd"]

[[example]]
name = "actix"
required-features = ["systemd", "with-actix-web"]

[lints]
workspace = true
