//! ISO 4217 currency identity. One register, three consumers.
//!
//! The register is generated by `build.rs`, which reads the maintenance agency's published
//! `list-one.xml` at compile time. There is no table here to edit, and no generated file to
//! keep in step: the XML in `vendor/` is the only place a currency fact exists.
//!
//! The build validates the register before emitting the enum and lookup tables.
//!
//! Credit and provenance -- source, publication date, capture date, checksum -- are in
//! `VENDORED.md`.

// `include!` rather than a `mod`: the generated code names `crate::StaticCurrency`
// and `crate::sealed::Sealed` relative to the crate root, so it has to expand at
// this path.
mod generated {
    // Generated tables naturally repeat exponent arms and name the enum being emitted.
    #![allow(clippy::match_same_arms, clippy::use_self)]

    include!(concat!(env!("OUT_DIR"), "/iso4217.rs"));
}

pub use generated::*;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn numeric_and_alpha3_agree() {
        assert_eq!(Iso4217::USD.numeric(), 840);
        assert_eq!(Iso4217::USD.alpha3(), "USD");
        assert_eq!(Iso4217::IDR.numeric(), 360);
        assert_eq!(Iso4217::IDR.alpha3(), "IDR");
    }

    #[test]
    fn exponents_are_iso_settlement_not_market_practice() {
        assert_eq!(Iso4217::USD.exponent(), Some(2));
        assert_eq!(Iso4217::JPY.exponent(), Some(0));
        assert_eq!(Iso4217::KWD.exponent(), Some(3), "Kuwaiti dinar has 3 minor digits");
        // IDR is 2 per ISO 4217 even though locale display commonly uses no fraction.
        assert_eq!(Iso4217::IDR.exponent(), Some(2));
    }

    #[test]
    fn metals_and_funds_have_no_exponent() {
        assert_eq!(Iso4217::XAU.exponent(), None, "gold has no cents");
        assert_eq!(Iso4217::XXX.exponent(), None);
    }

    #[test]
    fn lookups_round_trip() {
        for &c in Iso4217::EVERY {
            assert_eq!(Iso4217::from_numeric(c.numeric()), Some(c));
            assert_eq!(Iso4217::from_alpha3(c.alpha3()), Some(c));
        }
        assert_eq!(Iso4217::from_numeric(9999), None);
        assert_eq!(Iso4217::from_alpha3("ZZZ"), None);
        assert_eq!(Iso4217::from_alpha3("usd"), None, "case sensitive: ISO codes are uppercase");
    }

    #[test]
    fn every_is_alpha_sorted_not_numeric_ord_sorted() {
        assert!(
            Iso4217::EVERY.windows(2).all(|pair| pair[0].alpha3() < pair[1].alpha3()),
            "EVERY is the stable alpha-3 browsing order"
        );

        let aed = Iso4217::EVERY.iter().position(|code| *code == Iso4217::AED).unwrap();
        let all = Iso4217::EVERY.iter().position(|code| *code == Iso4217::ALL).unwrap();
        assert!(aed < all, "alpha order puts AED before ALL");
        assert!(Iso4217::AED > Iso4217::ALL, "derived Ord compares numeric discriminants: AED 784, ALL 8");
    }

    /// The register is generated, so what needs pinning is not the individual rows but the
    /// properties a regeneration could quietly break.
    ///
    /// The count is a snapshot of a published edition, not an invariant — ISO adds and
    /// withdraws codes. It is asserted anyway so that regenerating from a newer list is a
    /// deliberate act with a visible diff, rather than a silent change to what this crate
    /// considers money.
    #[test]
    fn the_register_matches_the_edition_it_was_generated_from() {
        assert_eq!(
            Iso4217::EVERY.len(),
            178,
            "ISO 4217 as published 2026-01-01 has 178 codes. If a regeneration changed this, \
             follow the ordered steps in VENDORED.md — and check what moved."
        );
        // The build gate counts parsed rows; this counts emitted variants.
    }

    /// Numeric and alpha-3 identities must be unique.
    #[test]
    fn no_two_currencies_share_an_identity() {
        let mut numerics: Vec<u16> = Iso4217::EVERY.iter().map(|c| c.numeric()).collect();
        numerics.sort_unstable();
        let before = numerics.len();
        numerics.dedup();
        assert_eq!(before, numerics.len(), "two currencies share a numeric code");

        let mut alphas: Vec<&str> = Iso4217::EVERY.iter().map(|c| c.alpha3()).collect();
        alphas.sort_unstable();
        let before = alphas.len();
        alphas.dedup();
        assert_eq!(before, alphas.len(), "two currencies share an alpha-3 code");
    }

    /// Shape invariants that hold for every edition, unlike the count.
    #[test]
    fn every_entry_is_well_formed() {
        for &c in Iso4217::EVERY {
            let a = c.alpha3();
            assert_eq!(a.len(), 3, "{a} is not three characters");
            assert!(a.bytes().all(|b| b.is_ascii_uppercase()), "{a} is not uppercase ASCII");
            assert!(!c.name().is_empty(), "{a} has no name");
            // 4 is the widest ISO uses (CLF). A larger value would mean a parse or generation
            // error, and would silently change what `text::render` pads to.
            if let Some(e) = c.exponent() {
                assert!(e <= 4, "{a} claims {e} minor digits");
            }
        }
    }

    /// Spot-checks against the published register, chosen to cover every exponent class.
    /// A regeneration that corrupted the exponent column would still satisfy every structural
    /// test above; these are the rows that would notice.
    #[test]
    fn the_exponent_classes_are_all_present_and_correct() {
        assert_eq!(Iso4217::JPY.exponent(), Some(0), "yen: no minor unit in use");
        assert_eq!(Iso4217::USD.exponent(), Some(2), "the ordinary case");
        assert_eq!(Iso4217::KWD.exponent(), Some(3), "Kuwaiti dinar: 1000 fils");
        assert_eq!(Iso4217::CLF.exponent(), Some(4), "Unidad de Fomento");
        assert_eq!(Iso4217::XAU.exponent(), None, "gold is not divided into cents");

        // ALL is the Albanian lek; keep it distinct from the `EVERY` collection.
        assert_eq!(Iso4217::ALL.numeric(), 8);
        assert_eq!(Iso4217::ALL.name(), "Lek");
    }
}
