//! ISO 4217 currency identity. One register, three consumers.
//!
//! The register is generated by `build.rs`, which reads the maintenance agency's published
//! `list-one.xml` at compile time. There is no table here to edit, and no generated file to
//! keep in step: the XML in `vendor/` is the only place a currency fact exists.
//!
//! What that deletes, concretely. A committed table needs a generator, a verifier, and a rule
//! that nobody hand-edits it -- three things that can each be skipped. Reading the register
//! during expansion collapses all of it: the register IS the table, its invariants are checked
//! as it is read, and a violation fails the build of everything downstream rather than a test
//! someone can `--skip`.
//!
//! Credit and provenance -- source, publication date, capture date, checksum -- are in
//! `VENDORED.md`.

// `include!` rather than a `mod`: the generated code names `crate::currency::StaticCurrency`
// and `crate::currency::private::Sealed` relative to the crate root, so it has to expand at
// this path. No `use` here on purpose — an import would be dead, and a reader who deleted it
// as unused would previously have broken the build, because the emitted code depended on it
// silently.
mod generated {
    // GENERATED CODE, LINTED AS IF HAND-WRITTEN. This is a cost of generating from a build
    // script rather than a proc macro: expanded macro output is largely exempt from clippy,
    // while an `include!`d file is ordinary source and every pedantic lint applies to it.
    //
    // Both of these are artefacts of a 178-arm generated table, not defects. Currencies that
    // share a minor-unit exponent produce identical match arms, and merging them would mean
    // emitting range patterns over a set whose membership is data. `use_self` fires where the
    // emitter names the enum it is defining.
    #![allow(clippy::match_same_arms, clippy::use_self)]

    include!(concat!(env!("OUT_DIR"), "/iso4217.rs"));
}

pub use generated::*;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn numeric_and_alpha3_agree() {
        assert_eq!(Iso4217::USD.numeric(), 840);
        assert_eq!(Iso4217::USD.alpha3(), "USD");
        assert_eq!(Iso4217::IDR.numeric(), 360);
        assert_eq!(Iso4217::IDR.alpha3(), "IDR");
    }

    #[test]
    fn exponents_are_iso_settlement_not_market_practice() {
        assert_eq!(Iso4217::USD.exponent(), Some(2));
        assert_eq!(Iso4217::JPY.exponent(), Some(0));
        assert_eq!(Iso4217::KWD.exponent(), Some(3), "Kuwaiti dinar has 3 minor digits");
        // IDR is 2 per ISO 4217 even though sen are extinct in practice. Display dp
        // (0) lives in LocalePolicy and is NOT this number. (DESIGN.md C2)
        assert_eq!(Iso4217::IDR.exponent(), Some(2));
    }

    #[test]
    fn metals_and_funds_have_no_exponent() {
        assert_eq!(Iso4217::XAU.exponent(), None, "gold has no cents");
        assert_eq!(Iso4217::XXX.exponent(), None);
    }

    #[test]
    fn lookups_round_trip() {
        for &c in Iso4217::EVERY {
            assert_eq!(Iso4217::from_numeric(c.numeric()), Some(c));
            assert_eq!(Iso4217::from_alpha3(c.alpha3()), Some(c));
        }
        assert_eq!(Iso4217::from_numeric(9999), None);
        assert_eq!(Iso4217::from_alpha3("ZZZ"), None);
        assert_eq!(Iso4217::from_alpha3("usd"), None, "case sensitive: ISO codes are uppercase");
    }

    /// The register is generated, so what needs pinning is not the individual rows but the
    /// properties a regeneration could quietly break.
    ///
    /// The COUNT is a snapshot of a published edition, not an invariant — ISO adds and
    /// withdraws codes. It is asserted anyway so that regenerating from a newer list is a
    /// deliberate act with a visible diff, rather than a silent change to what this crate
    /// considers money.
    #[test]
    fn the_register_matches_the_edition_it_was_generated_from() {
        assert_eq!(
            Iso4217::EVERY.len(),
            178,
            "ISO 4217 as published 2026-01-01 has 178 codes. If a regeneration changed this, \
             follow the ordered steps in VENDORED.md — and check what moved."
        );
        // NOT redundant with build.rs's edition gate, which counts what the PARSER found.
        // This counts what was EMITTED, so it also covers the expansion in between: a macro
        // that dropped or duplicated a variant would satisfy the gate and fail here.
    }

    /// Two currencies sharing a numeric code would make `from_numeric` lossy, and the binary
    /// serde form encodes exactly that number (C7). Verified at capture against the source;
    /// verified here against what actually compiled.
    #[test]
    fn no_two_currencies_share_an_identity() {
        let mut numerics: Vec<u16> = Iso4217::EVERY.iter().map(|c| c.numeric()).collect();
        numerics.sort_unstable();
        let before = numerics.len();
        numerics.dedup();
        assert_eq!(before, numerics.len(), "two currencies share a numeric code");

        let mut alphas: Vec<&str> = Iso4217::EVERY.iter().map(|c| c.alpha3()).collect();
        alphas.sort_unstable();
        let before = alphas.len();
        alphas.dedup();
        assert_eq!(before, alphas.len(), "two currencies share an alpha-3 code");
    }

    /// Shape invariants that hold for every edition, unlike the count.
    #[test]
    fn every_entry_is_well_formed() {
        for &c in Iso4217::EVERY {
            let a = c.alpha3();
            assert_eq!(a.len(), 3, "{a} is not three characters");
            assert!(a.bytes().all(|b| b.is_ascii_uppercase()), "{a} is not uppercase ASCII");
            assert!(!c.name().is_empty(), "{a} has no name");
            // 4 is the widest ISO uses (CLF). A larger value would mean a parse or generation
            // error, and would silently change what `text::render` pads to.
            if let Some(e) = c.exponent() {
                assert!(e <= 4, "{a} claims {e} minor digits");
            }
        }
    }

    /// Spot-checks against the published register, chosen to cover every exponent class.
    /// A regeneration that corrupted the exponent column would still satisfy every structural
    /// test above; these are the rows that would notice.
    #[test]
    fn the_exponent_classes_are_all_present_and_correct() {
        assert_eq!(Iso4217::JPY.exponent(), Some(0), "yen: no minor unit in use");
        assert_eq!(Iso4217::USD.exponent(), Some(2), "the ordinary case");
        assert_eq!(Iso4217::KWD.exponent(), Some(3), "Kuwaiti dinar: 1000 fils");
        assert_eq!(Iso4217::CLF.exponent(), Some(4), "Unidad de Fomento");
        assert_eq!(Iso4217::XAU.exponent(), None, "gold is not divided into cents");

        // ALL is the Albanian lek. Named here on purpose: it collided with the associated
        // const that used to be `Iso4217::ALL`, and a future edit reintroducing that name
        // would break `EVERY` in a way whose error message names neither.
        assert_eq!(Iso4217::ALL.numeric(), 8);
        assert_eq!(Iso4217::ALL.name(), "Lek");
    }
}
